# This Dockerfile is designed for testing MUSICA CCPP functionality.
# It includes:
# - Unit tests for MUSICA utility functions
# - Integration tests for MUSICA CCPP APIs

FROM ubuntu:22.04

# Commit on Nov 4th
ARG MUSICA_GIT_TAG=186bdfeda84565ebeae0d63dd20579e27711997f
# Commit on OCT 3rd
ARG CCPP_GIT_TAG=49a3c3fc221de993640ccc7b6f4a0efc8d0705a9

RUN apt update \
    && apt install -y sudo \
    && adduser test_user \
    && echo "test_user ALL=(root) NOPASSWD: ALL" >> /etc/sudoers.d/test_user \
    && chmod 0440 /etc/sudoers.d/test_user

USER test_user
WORKDIR /home/test_user

RUN sudo apt update \
    && sudo apt -y install \
    cmake \
    cmake-curses-gui \
    curl \
    g++ \
    gcc \
    gfortran \
    git \
    libblas-dev \
    liblapack-dev \
    lcov \
    libcurl4-openssl-dev \
    libhdf5-dev \
    libnetcdff-dev \
    libopenmpi-dev \
    m4 \
    make \
    nlohmann-json3-dev \
    openmpi-bin \
    python3 \
    tree \
    valgrind \
    vim \
    zlib1g-dev \
    && sudo apt clean

ENV PATH="${PATH}:/usr/lib/openmpi/bin"

ENV FC=mpif90
ENV FFLAGS="-I/usr/include/"

# Install MUSICA (MUSICA-C)
RUN git clone https://github.com/NCAR/musica.git

RUN cd musica \
    && git fetch \
    && git checkout ${MUSICA_GIT_TAG} \
    && cmake \
        -S . \
        -B build \
        -D CMAKE_BUILD_TYPE=Release \
        -D MUSICA_ENABLE_TESTS=OFF \
        -D MUSICA_BUILD_FORTRAN_INTERFACE=OFF \
        -D MUSICA_ENABLE_MICM=ON \
        -D MUSICA_ENABLE_TUVX=ON \
    && cd build \
    && sudo make install

COPY . atmospheric_physics
RUN sudo chown -R test_user:test_user atmospheric_physics

# Must make ccpp-framework available before building test
RUN cd atmospheric_physics/test \
    && mkdir lib \
    && cd lib \
    && git clone https://github.com/NCAR/ccpp-framework.git \
    && cd ccpp-framework \
    && git checkout ${CCPP_GIT_TAG}
ENV CCPP_SRC_PATH="lib/ccpp-framework/src"
ENV CCPP_FORTRAN_TOOLS_PATH="lib/ccpp-framework/scripts/fortran_tools"

RUN cd atmospheric_physics/test \
    && cmake -S . \
             -B build \
             -D CMAKE_BUILD_TYPE=Debug \
             -D CCPP_ENABLE_MUSICA_TESTS=ON \
             -D CCPP_ENABLE_MEMCHECK=ON \
    && cmake --build ./build

RUN cd atmospheric_physics/test \
    && mkdir third_party \
    && cd third_party \
    && git clone --depth 1 https://github.com/NCAR/tuv-x.git \
    && cp -r tuv-x/data ../build/data

WORKDIR /home/test_user/atmospheric_physics/test/build