FROM ubuntu:22.04

RUN apt update \
    && apt -y install \
    cmake \
    cmake-curses-gui \
    curl \
    libcurl4-openssl-dev \
    libhdf5-dev \
    m4 \
    nlohmann-json3-dev \
    vim \
    zlib1g-dev \
    git \
    lcov \
    make \
    libnetcdff-dev \
    valgrind \
    gcc \
    gfortran \
    g++ \
    tree \
    && apt clean

ENV FC=gfortran
ENV FFLAGS="-I/usr/include/"

RUN curl -LO https://github.com/jacobwilliams/json-fortran/archive/8.2.0.tar.gz \
    && tar -zxvf 8.2.0.tar.gz \
    && cd json-fortran-8.2.0 \
    && mkdir build \
    && cd build \
    && cmake -D SKIP_DOC_GEN:BOOL=TRUE .. \
    && make install

ENV JSON_FORTRAN_HOME="/usr/local/jsonfortran-gnu-8.2.0"

# Install MUSICA (MUSICA-C)
RUN git clone --depth 1 https://github.com/NCAR/musica.git
RUN cd musica \
    && cmake \
        -S . \
        -B build \
        -D USE_MUSICA=ON \
        -D USE_MUSICA_FORTRAN=OFF \
        -D MAKE_MUSICA_FORTRAN_INSTALLABLE=ON \
        -D ENABLE_MICM=ON \
        -D ENABLE_TESTS=OFF \
        -D ENABLE_TUVX=OFF \
    && cd build \
    && make install -j 8

RUN ln -s /usr/local/musica-0.5.0/lib/libmusica.a /usr/local/lib/libmusica.a
ENV MUSICA_VERSION="0.5.0"

COPY . atmospheric_physics

RUN cd atmospheric_physics/test \
    && mkdir lib \
    && cd lib \
    && git clone -b CPF_0.2.051 --depth 1 https://github.com/peverwhee/ccpp-framework.git
ENV CCPP_SRC_PATH="lib/ccpp-framework/src"

RUN cd atmospheric_physics/test \
    && cmake -S. \
             -B build \
             -D ENABLE_MICM_TEST=ON \
    && cmake --build ./build

RUN cd atmospheric_physics \
    && cp -r test/musica/micm/configs/chapman ./test/build/chapman

WORKDIR atmospheric_physics/test/build