# This Dockerfile is designed for testing MUSICA CCPP functionality.
# It includes:
# - Unit tests for MUSICA utility functions
# - Integration tests for MUSICA CCPP APIs
#
# No MUSICA library installation is required, as the CMake FetchContent module
# retrieves the MUSICA library automatically.

FROM ubuntu:latest

# Commit on Nov 5
ARG MUSICA_GIT_TAG=5b2e2f5b4afb5f7cbdc7112407d31b447bd891dd
# Commit on OCT 22
ARG CCPP_GIT_TAG=b7d55fd07fa35c5de9b2292596d30784a800b276

RUN apt update \
    && apt install -y sudo \
    && useradd test_user \
    && echo "test_user ALL=(root) NOPASSWD: ALL" >> /etc/sudoers.d/test_user \
    && chmod 0440 /etc/sudoers.d/test_user

USER test_user
WORKDIR /home/test_user

RUN sudo apt update \
    && sudo apt -y install \
    cmake \
    cmake-curses-gui \
    curl \
    g++ \
    gcc \
    gfortran \
    git \
    libblas-dev \
    liblapack-dev \
    lcov \
    libcurl4-openssl-dev \
    libhdf5-dev \
    libnetcdff-dev \
    libopenmpi-dev \
    m4 \
    make \
    openmpi-bin \
    python3 \
    tree \
    valgrind \
    vim \
    zlib1g-dev \
    && sudo apt clean

ENV PATH="${PATH}:/usr/lib/openmpi/bin"

ENV FC=mpif90
ENV FFLAGS="-I/usr/include/"
ENV MUSICA_GIT_TAG=${MUSICA_GIT_TAG}

COPY . atmospheric_physics
RUN sudo chown -R test_user:test_user atmospheric_physics

# Must make ccpp-framework available before building test
RUN cd atmospheric_physics/test \
    && mkdir lib \
    && cd lib \
    && git clone https://github.com/NCAR/ccpp-framework.git \
    && cd ccpp-framework \
    && git checkout ${CCPP_GIT_TAG}
ENV CCPP_SRC_PATH="lib/ccpp-framework/src"
ENV CCPP_FORTRAN_TOOLS_PATH="lib/ccpp-framework/scripts/fortran_tools"

RUN cd atmospheric_physics/test \
    && cmake -S . \
             -B build \
             -D CMAKE_BUILD_TYPE=Debug \
             -D CCPP_ENABLE_MUSICA_TESTS=ON \
             -D CCPP_ENABLE_MEMCHECK=ON \
    && cmake --build ./build

RUN cd atmospheric_physics/test \
    && mkdir third_party \
    && cd third_party \
    && git clone --depth 1 https://github.com/NCAR/tuv-x.git \
    && cp -r tuv-x/data ../build/data

WORKDIR /home/test_user/atmospheric_physics/test/build